### ISSUE TITLE
What is the difference between the 'InfoMetIC+' and 'InfoMetIC+CLIPScore'

### ISSUE THREAD

**Issue by bigbrother001** [HAWLYQ/InfoMetIC#2]
It looks like that InfoMetIC+ is not an independent metric because Formula 11 in the paper means sum InfoMetIC and CLIPScore, isn't it？

**Comment by HAWLYQ** [comment]
Yes, as shown in our paper, combining these two metrics achieves a better correlation with humans.

**Comment by bigbrother001** [comment]
Thanks!
